### ISSUE TITLE
Favicon and logo

### ISSUE THREAD

**Issue by peterpeterparker** [fluster/deckdeckgo#1]
Currently the project doesn't contains a favicon and logo. I've ask a friend to quick and dirty build one in order to be able to unleash this icon as open source under MIT licence too :)

P.S.: Note for myself, use https://realfavicongenerator.net to generate the icons

**Comment by peterpeterparker** [comment]
The icons are also a must to be able to unleash the "Add to home screen" feature

https://developers.google.com/web/fundamentals/app-install-banners/

**Comment by richardbmx** [comment]
@peterpeterparker  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by peterpeterparker** [comment]
@richardbmx thx for the proposition Richard, but no need. Like I said above, I asked my friend and she already began to work on it
